# Generated by Django 5.2.6 on 2025-11-07 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_roles', models.JSONField(default=list, help_text='List of job roles to search for')),
                ('locations', models.JSONField(default=list, help_text='List of locations to search for')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_jobs_scraped', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_link', models.URLField(max_length=1000)),
                ('posted_date', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='openings.scrapingsession')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
