# Generated by Django 5.2.6 on 2025-11-09 08:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('categories', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
                ('total_jobs_scraped', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
            ],
            options={
                'db_table': 'scraping_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Advocate', 'Advocate'), ('Arts', 'Arts'), ('Automation Testing', 'Automation Testing'), ('BlockChain', 'BlockChain'), ('Business Analyst', 'Business Analyst'), ('Civil Engineer', 'Civil Engineer'), ('Data Science', 'Data Science'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('.Net', '.Net'), ('ETL', 'ETL'), ('Electrical', 'Electrical'), ('HR', 'HR'), ('Hadoop', 'Hadoop'), ('Health and Fitness', 'Health and Fitness'), ('Java', 'Java'), ('Mechanical', 'Mechanical'), ('Network', 'Network'), ('Operations', 'Operations'), ('PMO', 'PMO'), ('Python', 'Python'), ('SAP', 'SAP'), ('Sales', 'Sales'), ('Testing', 'Testing'), ('Web Design', 'Web Design')], max_length=50, null=True)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date_posted', models.CharField(max_length=100)),
                ('job_link', models.URLField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='openings.scrapingsession')),
            ],
            options={
                'db_table': 'job_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
