# Generated by Django 5.2.6 on 2025-11-07 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='scraped_at',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='date_posted',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='joblisting',
            table='job_listings',
        ),
        migrations.DeleteModel(
            name='ScrapingSession',
        ),
    ]
