# Generated by Django 5.2.6 on 2025-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_remove_joblisting_session_alter_joblisting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='category',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
